"""Generates METRICS.md and RUN_LOG.txt from results.json, the executed notebook and logs/console.log.

Run from hw6/ after the full notebook run:  .venv/bin/python make_reports.py
"""
import json

R = json.load(open("results.json"))
NB = json.load(open("ssl_stl10.ipynb"))
MODELS = ["Supervised", "Rotation SSL", "SimCLR"]
CLASSES = ["airplane", "bird", "car", "cat", "deer", "dog", "horse", "monkey", "ship", "truck"]
H = R["histories"]

code_cells = [c for c in NB["cells"] if c["cell_type"] == "code"]
errors = [o for c in code_cells for o in c.get("outputs", []) if o.get("output_type") == "error"]

m = []
m.append("# HW6 Metrics\n")
m.append(f"SID4 = {R['SID4']}, SEED = {R['SEED']}. Every number below is read from `results.json`, which the final "
         f"executed run of `ssl_stl10.ipynb` wrote ({len(errors)} cell errors in {len(code_cells)} code cells; see "
         "`RUN_LOG.txt`). This file is generated by `make_reports.py`, not typed by hand.\n")
m.append("## Setup\n")
m.append("| Item | Value |\n|---|---|")
m.append("| Backbone (all parts) | torchvision ResNet-18, `weights=None`, `fc = Identity` → 512-d embedding (11,176,512 params) |")
m.append("| Labeled subset | 500 train images, 50 per class, sampled with SEED; same subset for A, B and C |")
m.append("| Part A | end-to-end, 15 epochs, AdamW lr 1e-3, wd 5e-4, batch 32, cosine; crop (0.5–1.0) + flip |")
m.append("| Part B pretext | 4-way rotation (0/90/180/270°), all 100,000 unlabeled images, 15 epochs, SGD-Nesterov lr 0.1, wd 5e-4, batch 256, 1-epoch warm-up + cosine |")
m.append("| Part C pretext | SimCLR, 20,000 unlabeled images (SEED), 20 epochs, NT-Xent with cosine similarity, τ = 0.2, projection MLP 512→512→128, AdamW lr 1e-3, batch 256 (512 views) |")
m.append("| SimCLR augmentations | RandomResizedCrop(96, 0.2–1.0), HorizontalFlip, ColorJitter(0.4, 0.4, 0.4, 0.1) p=0.8, Grayscale p=0.2 |")
m.append("| Linear probe (B, C) | frozen encoder (eval mode, no grad); `Linear(512, 10)` only, 5,130 trainable params; 20 epochs, Adam lr 1e-3, batch 32 |")
m.append("| Test set | all 8,000 STL-10 test images |")
m.append("| Hardware | Apple M1 (MPS), 16 GB unified memory |\n")

m.append("## Main results (test set, 8,000 images)\n")
m.append("| Model | Test accuracy | kNN precision@5 (cosine) | Retrieval failures (0/5 same class) | Training time |")
m.append("|---|---|---|---|---|")
for n in MODELS:
    f = R["retrieval_failures"][n]
    m.append(f"| {n} | **{R['test_accuracy'][n]:.4f}** | {R['precision_at_5'][n]:.4f} | "
             f"{f['n_zero']:,} ({f['frac_zero']:.1%}) | {R['train_time_min'][n]:.1f} min |")
m.append("\nChance is 0.10 for both accuracy and precision@5. Training time covers pretraining (B, C) or end-to-end "
         "training (A), not the linear probe, which takes seconds.\n")

m.append("## Training curves (per-epoch training loss)\n")
m.append("| Epoch | A: CE loss | A: train acc | B: rotation loss | B: rotation acc | C: NT-Xent loss | C: positive top-1 |")
m.append("|---|---|---|---|---|---|---|")
for e in range(max(len(H["A"]), len(H["B"]), len(H["C"]))):
    a = H["A"][e] if e < len(H["A"]) else {}
    b = H["B"][e] if e < len(H["B"]) else {}
    c = H["C"][e] if e < len(H["C"]) else {}
    cell = lambda d, k: f"{d[k]:.4f}" if k in d else ""
    m.append(f"| {e + 1} | {cell(a, 'loss')} | {cell(a, 'train_acc')} | {cell(b, 'loss')} | {cell(b, 'rot_acc')} | "
             f"{cell(c, 'loss')} | {cell(c, 'pos_top1')} |")
m.append("")

m.append("## Linear probe (final epoch, 500 training embeddings)\n")
m.append("| Encoder | Probe train loss | Probe train acc | Test accuracy |\n|---|---|---|---|")
for n, k in [("Rotation SSL", "probeB"), ("SimCLR", "probeC")]:
    last = H[k][-1]
    m.append(f"| {n} | {last['loss']:.4f} | {last['train_acc']:.3f} | {R['test_accuracy'][n]:.4f} |")
m.append("")

m.append("## Per-class test accuracy\n")
m.append("| Class | " + " | ".join(MODELS) + " |\n|---|" + "---|" * len(MODELS))
for c, name in enumerate(CLASSES):
    m.append(f"| {name} | " + " | ".join(f"{R['per_class_accuracy'][n][c]:.3f}" for n in MODELS) + " |")
m.append("\n**Most frequent confusions (true → predicted, fraction of the true class):**\n")
for n in MODELS:
    m.append(f"- {n}: " + "; ".join(f"{t} → {p} ({v:.2f})" for t, p, v in R["top_confusions"][n]))
m.append("")

m.append("## Part D: nearest-neighbour queries\n")
m.append(f"Query test indices (drawn with SEED from four distinct classes): {R['query_indices']}\n")
m.append("| Encoder | Same-class neighbours out of 5, per query |\n|---|---|")
for n in MODELS:
    m.append(f"| {n} | {R['query_hits'][n]} |")
m.append("")
m.append("**Classes with the most retrieval failures:**\n")
for n in MODELS:
    m.append(f"- {n}: " + ", ".join(f"{c} ({k})" for c, k in R["retrieval_failures"][n]["by_class"]))
open("METRICS.md", "w").write("\n".join(m) + "\n")

# RUN_LOG.txt: header + the timestamped console log of the run(s) that produced results.json
console = open("logs/console.log").read()
nbconv = open("logs/nbconvert.log").read()
log = ["HW6 RUN LOG", f"SID4={R['SID4']}  SEED={R['SEED']}",
       "Machine: Apple M1 MacBook (16 GB), macOS, MPS backend. See the environment lines at each RUN_START below.",
       "",
       "Notebook: ssl_stl10.ipynb, executed top-to-bottom with no manual intervention via ./run_full.sh:",
       "  .venv/bin/jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.kernel_name=hw6 \\",
       "      --ExecutePreprocessor.timeout=-1 ssl_stl10.ipynb",
       "",
       "Checkpoints: each part saves checkpoints/<part>.pt, and a re-run loads it instead of retraining. Parts B and C",
       "also save a per-epoch progress checkpoint so an interrupted run resumes after the last finished epoch.",
       "",
       f"Final executed notebook: {len(errors)} cell errors in {len(code_cells)} code cells.",
       "",
       "=" * 80, "INTERRUPTIONS AND RESTARTS (all attempts are kept below, unedited)", "=" * 80,
       "- Attempt 1 (2026-10-07 22:25 PDT): Part A trained and saved its checkpoint (test acc logged below). The run was",
       "  killed at rotation epoch 3 of 15 when the Claude Code session that launched it exited, since the job was a child",
       "  of that session. No error and no stack trace: the process was terminated.",
       "- Fix: the run was relaunched fully detached (own process session, ./run_full.sh), with per-epoch resume",
       "  checkpoints added for Parts B and C. Part A was loaded from its checkpoint, not retrained.",
       "",
       "=" * 80, "CONSOLE LOG (logs/console.log: every log() line, timestamped)", "=" * 80, console,
       "=" * 80, "NBCONVERT LOG (logs/nbconvert.log)", "=" * 80, nbconv]
open("RUN_LOG.txt", "w").write("\n".join(log) + "\n")
print("wrote METRICS.md and RUN_LOG.txt")
